### ISSUE TITLE
Certain websites' custom scrollbars are rendered wrong in Thorium 115

### ISSUE THREAD

**Issue by Delphox** [Alex313031/Thorium-Win#59] opened 2023-08-14 15:55 UTC
**System Details**
 - OS: Windows 10 22H2
 - Thorium Version 115.0.5790.172

**Problem**
Starting on version 115, certain websites that use custom scrollbars such as Youtube Studio and Discord show a generic scrollbar instead which looks very out of place.

**Screenshots**
Discord:
![image](https://github.com/Alex313031/Thorium-Win/assets/5883538/9a5511d2-e4b8-4586-8dcb-3a5dfee5c651)
Youtube Studio:
![image](https://github.com/Alex313031/Thorium-Win/assets/5883538/112cee55-dd55-4df7-b145-86863c4791d3)

**Additional Notes**
I have tested vanilla Chrome 115, and confirmed that the scrollbars render correctly there.

**Comment by gz83** [comment] 2023-08-15 12:36
Check whether there is an extension or experimental function flag related to scroll bar rendering. If so, you need to close it and check the scroll bar rendering again.

Also, please upload an image that renders the scrollbars correctly.

@Delphox

**Comment by Delphox** [comment] 2023-08-16 02:11
> Also, please upload an image that renders the scrollbars correctly.

Youtube Studio:
![image](https://github.com/Alex313031/Thorium-Win/assets/5883538/c7edd3f1-e2cf-4315-ad0a-0d07b8aa76ec)
Discord:
![image](https://github.com/Alex313031/Thorium-Win/assets/5883538/a5105645-92a4-40e4-8284-fcc86929ba8e)

It can also be observed on the Youtube homepage on Dark mode, it affects the left menu (where you can choose Home, Shorts, Subscriptions etc).

Interesting that you mention experimental flags, cuz I went and removed --enable-experimental-web-platform-features from the THORIUM.BAT launch arguments and the scrollbars look correct again. Not only that, but enabling that flag on vanilla Chrome does cause the same wrong scrollbars. That behavior was also observed when enabling that flag on Chromium 116 and 117. So we can confirm the issue originates from that flag starting on Chromium 115.

So although this is something on Chromium side, it does affect Thorium Portable out of the box as the enable-experimental-web-platform-features flag is one of the arguments in the launch bat.

Would it be a big loss dropping that flag @Alex313031 ? Not sure what exactly it brings or if some Thorium feature rely on it or something.

**Comment by Alex313031** [comment] 2023-08-16 04:58
@Delphox @gz83 Looks like the same issues we have with dark mode text selection. Where CSS meta-elements for font and scrollbars don't work correctly because Chromium rolled a third_party dep for rendering this stuff. I will remove the experimental web platform features from linux and windows releases. You can still enable it on chrome://flags.

**Comment by gz83** [comment] 2023-08-16 05:05
If this experimental feature flag is turned on, some relatively new feature specifications (mainly affecting Blink rendering and layout engines) will be enabled, and these new feature specifications have not been supported by Chromium or have a low level of support, which can cause Chromium to experience abnormal situations on certain web pages (such as being unable to correctly present the highlighted content selection effect under certain conditions).

Based on my daily observations, it can be seen that turning off this experimental feature flag has no adverse impact on browser usage and performance. If you encounter problems, as mentioned in this issue, you can try turning off this experimental feature flag.

@Delphox

**Comment by Alex313031** [comment] 2023-08-16 05:07
@Delphox @gz83 I have removed all experimental web platform features for all platforms.

https://github.com/Alex313031/thorium/commit/d3a7696089cb0b60fad126060502e6d19058a6c9

**Comment by Alex313031** [comment] 2023-08-16 19:00
@Delphox Are you saying the text selection bug appeared on telegram?

And yeah, unfortunately I had just released the Windows releases when you filed this bug. M116 will have the fix though.

**Comment by Delphox** [comment] 2023-08-16 21:04
> Are you saying the text selection bug appeared on telegram?

Yes, especifically the K version of Telegram Web (there's a K version and A version that you can switch back and forth, K has a few missing features but is a lot slicker and loads a lot faster).


> And yeah, unfortunately I had just released the Windows releases when you filed this bug. M116 will have the fix though.

Well it was the latest release that brought the scrollbar bug that made we look into this in first place we'll take it. :)

**Comment by gz83** [comment] 2023-08-17 00:57
The issue caused by this experimental flag should still not be resolved in the new version, and we may need to continue disabling this experimental flag

@Delphox @Alex313031

**Comment by Alex313031** [comment] 2023-08-18 23:26
@gz83 What do you mean? Are you saying removing the flag isn't fixing it?

**Comment by gz83** [comment] 2023-08-19 01:11
> @gz83 What do you mean? Are you saying removing the flag isn't fixing it?

What I mean is that turning on the `experimental web platform features` experimental flag may cause some problems with the rendering of web page elements. There are some issue reports on crbug about turning on this experimental flag and destroying the rendering of web page elements.

To fix these damaged web page elements, we need to wait for chromium to fix it at the blink engine level, but it seems that chromium is not making progress in this regard very quickly, and we still need to wait for a while.

Based on the above, I think that if we encounter problems with the rendering of web page elements after turning on this experimental flag, we'd better turn off this experimental flag, which is consistent with the effect of deleting this experimental flag from the startup parameters

@Alex313031

**Closed** 2023-08-23 20:00 UTC
