### ISSUE TITLE
New Tab Page is broken if selected search engine is other than Google

### ISSUE THREAD

**Issue by Unknown78** [Alex313031/Thorium-Win#181] opened 2024-03-06 06:44 UTC
## Backgrounds
- OS: Windows 11 Pro for Workstations x64 23H2 v10.0.22631.3155
- App Version: [Thorium_SSE3_121.0.6167.204.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M121.0.6167.204)
- Default Browser Flags

## Problems
I'll use `DuckDuckGo` in this issue as an example.
But it doesn't have to be, try `Bing` or `Yandex` or others also have the same issue.

1. Go to `Settings > Search Settings`  or chrome://settings/search
2. Change `Search engine used in the address bar.` to `DuckDuckGo`
3. Open `New Tab` or chrome://newtab

There should be `Customize` menu where you could disable `Most Visited Sites`.

## Screenshots of [Thorium_SSE3_121.0.6167.204.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M121.0.6167.204)
![Screenshot of Thorium_SSE3_121.0.6167.204.zip](https://github.com/Alex313031/Thorium-Win/assets/25132599/2db12e41-8344-4ac3-b43f-03c2e6a47d56)

## Screenshots of [GoogleChromePortable_122.0.6261.95_online.paf.exe](https://sourceforge.net/projects/portableapps/files/Google%20Chrome%20Portable/)
![Screenshots of GoogleChromePortable_122.0.6261.95_online.paf.exe](https://github.com/Alex313031/Thorium-Win/assets/25132599/18b1474e-0055-4b5c-84f7-f274a786eae5)

<hr>
Might be related: #108

**Comment by Alex313031** [comment] 2024-03-25 16:38
@Unknown78 Fixed in https://github.com/Alex313031/thorium/commit/e11300316f324c389fe513f12911014d3e1d605c

**Closed by Alex313031** 2024-03-25 16:38 UTC

**Comment by Unknown78** [comment] 2025-03-15 07:47
@gz83 @Alex313031 

I forgot to report this, but there's seems to be a regression.
Not sure since when, but in v128 and v130 I've observed the same NTP bug, so this issue need to be reopened again.

**Comment by faizul726** [comment] 2025-04-09 09:25
The issue is happening again on 130.
See https://github.com/Alex313031/thorium/issues/576#issuecomment-2788957776

**Comment by Unknown78** [comment] 2026-01-06 09:18
It's fixed again on Thorium 138

Tested with [thorium_SSE4_138.0.7204.300.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M138.0.7204.300)

**Comment by faizul726** [comment] 2026-01-09 07:02
> It's fixed again on Thorium 138
> 
> Tested with [thorium_SSE4_138.0.7204.300.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M138.0.7204.300)

Can confirm it's fixed @Unknown78 


<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5f2aadcc-7966-4a5e-a1dc-c22a8f5323a2" />
